src/mainwindow.cc

Wrote the code for clearing the input and output boxes on launching a new session [Issue #9](https://github.com/coder3101/cp-editor2/issues/9)

Fixes #9 : Output and input box clears on New Session

---

src/main.cc

In the old version, you can't open a file with Unicode in its path (Ctrl+O works well, but opening by the command-line argument doesn't). This PR fixes it.

fix(main): open file with unicode in path

---

src/mainwindow.cc

fix(mainwindow): use simplified instead of trimmed in diff

---

include/mainwindow.hpp
src/mainwindow.cc

fixes #38
This function ignores whitespaces at the back of a line and lines consisted of only whitespaces at the bottom.

fix(mainwindow): implement isVerdictPass for diff

---

include/mainwindow.hpp
src/mainwindow.cc

This fixes the second part of #23.
It's a big change, I'm not so sure that there aren't any mistakes. Please check it carefully.
BTW, the code reuse is terrible. There are too many copy pastings, especially the 3 inputs, 3 outputs, 3 runners part.

feat(mainwindow): update saving logic & detect text change

---

src/mainwindow.cc

1. fix the bug of saving a file as itself.
2. Use saveFile() for save as, more code reuse.
3. change openFile to the file saved as, which is the same as many other editors/IDEs.

fix(mainwindow): update save as

---

src/MessageLogger.cpp

In the old version, if you click in the messageLogger, the place of the "cursor" will change, and new logs will be inserted after the "cursor".

fix(MessageLogger): use append instead of insertHtml 

---

src/mainwindow.cc

I think it should be my mistake when using git. I remember this setting is restored when I tested it locally. 😢

fix(mainwindow.cc): restore save tests setting

---

src/MessageLogger.cpp

Compiler messages like `vector<int>` should be HTMLescaped.

feat(MessageLogger): make messages HTMLescaped

---

include/SettingsManager.hpp
include/appwindow.hpp
include/mainwindow.hpp
src/CompanionServer.cpp
src/SettingsManager.cpp
src/appwindow.cpp
src/main.cc
src/mainwindow.cc
ui/appwindow.ui

See the commit messages for more information.

Some changes about tabs

---

include/Runner.hpp
src/Runner.cpp

I got this from building:
D:\GitHub\cp-editor\src\Runner.cpp(311): warning C4996: 'QTime::start':
Use QElapsedTimer instead [D:\GitHub\cp-editor\build\CPEditor.vcxproj]
D:\GitHub\cp-editor\src\Runner.cpp(337): warning C4996: 'QTime::elapsed':
Use QElapsedTimer instead [D:\GitHub\cp-editor\build\CPEditor.vcxproj]
Maybe QElapsedTimer is a better choice.

chore(runner): use QElapsedTimer instead of QTime

---

include/SettingsManager.hpp
src/SettingsManager.cpp
src/mainwindow.cc
src/preferencewindow.cpp
ui/preferencewindow.ui

It was really confusing: `editor->setTabReplace(data.isTabsBeingUsed);`

refactor: tabs -> tabsReplaced

---

src/Formatter.cpp
src/SettingsManager.cpp
src/appwindow.cpp
src/preferencewindow.cpp

Don't know why, but use the output instead of `-i` fixes #80.
~~Please remind the users to change the format command. Or is it better to let the user choose clang-format binary and style instead of the whole command?~~ See f5efec8.
This PR also changes the way of applying the formatting to the editor, so that format won't clear undo history.

Formatter changes

---

include/SettingsManager.hpp
include/preferencewindow.hpp
src/SettingsManager.cpp
src/appwindow.cpp
src/preferencewindow.cpp

Sinces all defaults are in the "get" functions, a simple clear()
should do the resetting well.
What's more, this fixes the bug that unused settings won't be cleared.
For example, there is still "compile" without "cpp" in my ini file.

refactor: use QSettings::clear() for reset settings

---

README.md
include/Formatter.hpp
include/SettingsManager.hpp
include/UpdateNotifier.hpp
include/appwindow.hpp
include/preferencewindow.hpp
src/DiffViewer.cpp
src/Formatter.cpp
src/SettingsManager.cpp
src/appwindow.cpp
src/cftools.cpp
src/editortheme.cpp
src/expand.cpp
src/main.cc
src/mainwindow.cc
src/preferencewindow.cpp
ui/preferencewindow.ui

1. Set clang-format binary instead of set format command.
2. Use `--cursor` argument to keep the cursor after formatting.
3. Format selection only if there is a selection.
4. Set format style in preference window.
5. Add format on save option.
6. Open temporary file for formatting when necessary instead of holding it.
7. Other text changes and minor changes.
8. Modify README.md for these changes.
This closes #81 .

feat(formatter): clang-format update

---

include/appwindow.hpp
include/mainwindow.hpp
src/appwindow.cpp
src/mainwindow.cc
ui/mainwindow.ui

1. Open file when necessary instead of holding it.
2. Watch file changes on disk.
3. Show complete path when multiple tabs are of the same name.
4. Change language when saving unsaved files / saving as.
5. Text changes and other minor changes.
Please test these changes. I think there might be some bugs, especially when handling read/write file fails, and things related to problemURL.

feat: make file logic like Sublime

---

README.md
include/Core/Formatter.hpp
include/Core/SettingsManager.hpp
src/Core/Formatter.cpp
src/Core/SettingsManager.cpp

Pass methods arguments by const refs

---

include/Core/SettingsManager.hpp
src/Core/SettingsManager.cpp

Add a dot at the front of the name of the config file. Fixes #163.
If `cp_editor_settings.ini` is found on the home directory,
the contents are simply copied to `.cp_editor_settings.ini`,
and the old file is deleted.

Add a dot at the front of the name of the config file

---

CHANGELOG.md
src/Widgets/TestCases.cpp

The diff viewer was not showing line breaks.

Fixed #181 unexpected behavior of diff viewer

---

.github/workflows/check_format.yml

Auto create PR for Clang Format check.
In this way, we can fix wrong format more easily.
This is better than commit directly, because:
1. It works on protected branches.
2. We can choose to merge it or change it manually.
3. After the merge, CI will run on it. Though it won't before the merge, we can still revert/fix it easily after the merge.

ci(check_format): Auto create PR to fix format

---

doc/CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/Util.cpp
src/Util.hpp
src/Widgets/TestCase.cpp
src/Widgets/TestCase.hpp
src/Widgets/TestCases.cpp
src/Widgets/TestCases.hpp
src/mainwindow.cpp

- Now you can choose where to save the test case files in Preferences->File Path->Testcases.
- Now when saving the source file, if the parent directory of the file does not exist, it will be automatically created.
This resolves #176.
The files are in a mess if the test cases are saved in the same directory as the source file. With this feature, the user can save the test cases in a separate directory.
Tested on Manjaro KDE.

feat: Add choose where to save the test case files

---

src/Settings/StringListsItem.cpp
src/Settings/StringListsItem.hpp

The Unicode characters in the buttons are replaced by ASCII text.
I got compilation error on my Windows. Though perhaps this can be fixed by configuring the compiler, it shows that it's better not to use Unicode characters in the code.
On my WIndows 10.

fix(StringListsItem): Remove Unicode characters in the buttons

---

doc/CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/mainwindow.cpp

Now you can set different default file paths for different problem URLs.
This closes #200.
With this, users don't have to manually set the saving path when using Competitive Companion.

feat: Set different default file paths for different problem URLs

---

src/Settings/settings.json
src/mainwindow.cpp

The bug:
1. Empty regexes match everything.
2. If the regex matches only a part of the problem URL, other parts won't be replaced and will be in the saving path.
Now it's fixed.
And the tooltips are modified to point out that the regexes in the Testcases Matching Rules should match the whole string, and the regexes in Default File Paths For Problem URLs can match only a part of the problem URL.
The regexes in the Testcases Matching Rules should match the whole string, because it's common that a testcase file is a substring of another.
The regexes in Default File Paths For Problem URLs can match only a part of the problem URL, because it's nearly impossible that one problem URL is the substring of another, but sometimes there are suffixes like "#" or "?" in the problem URL, and users may …

fix(default save path): Ignore empty regex and replace captured string

---

doc/CHANGELOG.md

Fix Ctrl+Enter and Ctrl+Shift+Enter in the code editor.
Ctrl+Enter should be the same as End + Enter
Ctrl+Shift+Enter should be the same as Up + End + Enter if it's not at
the first line.
Now they work as expected.
On Manjaro KDE:
1. Ctrl+Enter
```
<cursor>{
```
Old:
```
{
<cursor>
```
Now:
```
{
<tab><cursor>
```
2. Ctrl+Enter
```
{<cursor>}
```
Old:
```
{
<tab><cursor>
}
```
Now:
```
{}
<cursor>
```
3. Ctrl+Shift+Enter
```
{
<cursor>
```
Old:
```
{
<cursor>
```
Now:
```
{
<tab><cursor>
```

Fix Ctrl+Enter and Ctrl+Shift+Enter

---

src/Settings/SettingsManager.cpp

Don't load invalid settings.
Empty QVariantList is saved as an invalid QVariant in the settings.
Though I don't know why it is invalid, it makes the setting always
modified when it's empty, and the user will be warned by unsaved
settings.

fix: Don't load invalid settings

---

src/mainwindow.cpp
src/mainwindow.hpp

Don't save non-exist files when getting the temp path.
Because of the language server, now the temp path is often requested.
However, a tab with a non-exist file path shouldn't be automatically saved. Like when opening a contest, or open a non-exist file in the terminal.

fix: Don't save non-exist file when getting temp path

---

doc/CHANGELOG.md
src/Settings/AppearancePage.cpp
src/Settings/settings.json
src/Util.cpp
src/Widgets/TestCase.cpp
src/Widgets/TestCase.hpp
src/Widgets/TestCaseEdit.cpp
src/Widgets/TestCases.cpp
src/Widgets/TestCases.hpp
src/mainwindow.cpp

Now users can set the font for test cases.
In the input of some problems, there's a board consisting of `.` and `*`, which requires a monospace font to be readable.
- [x I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.

feat: Set font for test cases

---

.github/workflows/push_aur.yml

Don't update `cpeditor-git` on non-code changes.
Reduce unnecessary updates for AUR users.

ci: Don't update cpeditor-git on non-code changes

---

src/Core/MessageLogger.cpp
src/Settings/AppearancePage.cpp
src/Settings/settings.json
src/mainwindow.cpp

Allow user to customize message logger font in case the message
contains non-ascii characters.
related issue: #331

feat: Support customizing message logger font

---

doc/CHANGELOG.md
src/Settings/PreferencesPageTemplate.cpp

Now you can search for the desc, tip and help of a setting in the preferences window.
In this way, it will be easier to search for a setting.

feat(Settings): Search desc, tip and help of a setting

---

doc/CHANGELOG.md
ui/appwindow.ui

Make it able to use Alt to choose the menu in the main window. For example, you can use "Alt+F" to choose the "File" menu.
Make it easier to choose the menu.
When pressing <kbd>Alt</kbd>:

feat: Use Alt to choose the menu in the main window

---

.github/stale.yml

Add config for the stale bot.
The app: https://github.com/apps/stale/
Use the bot to close inactive issues.
Don't mark issues with labels for the priority as stale issues.

chore: add config for the stale bot

---

src/Extensions/EditorTheme.cpp
src/Extensions/EditorTheme.hpp
src/Util.cpp

Combine getXXXTheme() functions to query(QString).
Make it easier and simpler to add new themes.

refactor: Improve style mapping

---

README.md
README_zh-CN.md
doc/CHANGELOG.md
doc/MANUAL.md
doc/MANUAL_zh-CN.md
src/Core/Checker.cpp
src/Core/Compiler.cpp
src/Core/Compiler.hpp
src/Core/Runner.cpp
src/Core/Runner.hpp
src/Settings/PreferencesHomePage.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp

- Now it's optional to save the file on compilation and execution or not.
- Now you can choose the path of the executable file of C++. (#271)
- Fixed some unexpected file saving. (#353)
- Open an empty untitled tab when the open file length limit is exceeded. (#353)
Close #271, fix #353.
See #353.
On Manjaro KDE, tested on some basic usage.

Fix #271 and #353

---

CMakeLists.txt
cmake/gitsha.hpp.in
cmake/version.hpp.in
doc/CHANGELOG.md
src/Core/EventLogger.cpp
src/appwindow.cpp
src/main.cpp

Display git commit hash in `cpeditor --version`, `gitsha.hpp` is also moved into `version.hpp`.
Can get the commit hash without opening in GUI.

feat: display git commit hash in `cpeditor --version`

---

.github/ISSUE_TEMPLATE/config.yml
README.md
README_ru-RU.md
README_zh-CN.md

The old one has expired, and the new one will never expire.

docs: fix Slack link

---

.ci/aur/.SRCINFO
.ci/aur/PKGBUILD
.github/workflows/release_aur.yml
cmake/aur/.SRCINFO.in
cmake/aur/PKGBUILD.in

According to https://wiki.archlinux.org/index.php/PKGBUILD#makedepends :
> The group [base-devel](https://www.archlinux.org/groups/x86_64/base-devel/) is assumed to be already installed when building with *makepkg*. Members of this group **should not** be included in `makedepends` array.
And remove the compiler setting makes it possible to use other compilers like clang or ccache.

build: Update AUR packages

---

.ci/aur/.SRCINFO
.ci/aur/PKGBUILD
cmake/aur/.SRCINFO.in
cmake/aur/PKGBUILD.in
tools/genSRCINFO.sh

I use the format
```
(
...
...
)
```
because in this way the items are aligned and each change only affects one line.
[cf-tool](https://aur.archlinux.org/packages/cf-tool) is in AUR so I added it.

build(aur): add optdepends and a script to generate .SRCINFO

---

CMakeLists.txt
doc/CHANGELOG.md
src/Settings/FileProblemBinder.cpp
src/Settings/FileProblemBinder.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsManager.cpp
src/Settings/settings.json
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp

Now you can restore the problem URL when opening a file previously with a problem URL, and/or open the old file when parsing an old problem URL.
This closes #199.

feat: add bind file and problem

---

.github/workflows/push_aur.yml

Don't update AUR in forks.
Now CI fails in forks because there's no SSH key of the AUR repo in forks.

ci(aur): don't update AUR in forks

---

doc/CHANGELOG.md

Fix the screen is not scrolled to show the cursor in some situations.
---
I think this is not very important so it's OK to only apply this to the master branch :thinking:.

fix(QCodeEditor): scroll to show the cursor

---

.ci/aur/PKGBUILD
cmake/aur/PKGBUILD.in

1. Add quotes to variables.
2. Fix `_pkgdir` in the stable release PKGBUILD.

build(aur): add quotes to variables and fix $_pkgdir

---

doc/CHANGELOG.md
src/mainwindow.cpp
src/mainwindow.hpp
ui/mainwindow.ui

Added a button to clear the messages.
"Messages and stderr" is also changed to "Messages", otherwise, it
will be the bottleneck of the minimum width.

feat(MainWindow): add a button to clear the message logger

---

doc/CHANGELOG.md
src/Widgets/TestCase.cpp
src/Widgets/TestCases.cpp
src/appwindow.cpp
src/mainwindow.cpp

1. When parsing a problem while it is already parsed and opened in a tab, the new test cases will override the old test cases.
2. The file bound with a problem will be opened only when it's readable (which implies it exists).
3. Fix the bug that the cursor position is reset when applying competitive companion, which breaks the initial cursor position for the template.

refactor: improve apply competitive companion

---

doc/CHANGELOG.md
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp

If you click "Cancel" when saving all files, the action will be aborted instead of saving the next file.
1 .If you are in a contest and you accidentally triggered Save All, you want to cancel it in one click.
2. If you do want to save all files, but found something incorrect (some files are saved to the wrong place, etc.) so you want to abort the whole action, fix that error, and then continue.

feat: abort saving all when cancelling one

---

doc/CHANGELOG.md
src/Settings/CodeSnippetsPage.cpp
src/Settings/CodeSnippetsPage.hpp

Ask whether to override an existing snippet or not when there's a conflict in the snippet names.
This closes #244.
As an instance, I may want to import snippets from files, and I want to override the old ones, instead of deleting the old ones and then import.

feat(Settings): ask whether to override the snippet with the same name

---

.ci/linux/cpeditor.desktop
.github/workflows/release_linux.yml

Since the icon already is installed to a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) you don't need to specify the full icon path or the file type extension in the launcher. 
The icon will be found anyway (without renaming anything).
Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example) presented in the freedesktop.org documentation.

build: Unhardcode icon file type for Linux launcher

---

src/Settings/SettingsManager.cpp
src/Widgets/TestCase.cpp

Don't log the content of test cases and snippets.
They can make the log files extremely large.
On Arch Linux.

refactor: fewer logs

---

doc/CHANGELOG.md
src/Widgets/TestCases.cpp

Now the lengths of the files added by "Add Pairs of Testcases From Files" are limited by Preferences->Advanced->Limits->Load Test Case File Length Limit.

feat: limit the lengths of files in "Add Pairs of Testcases From Files"

---

tools/newFile.sh
tools/newReleaseCycle.sh

Change /bin/sh to /bin/bash.
These two scripts use the feature provided by bash.
On some systems /bin/sh links to dash, which cannot run the script.

fix: Use /bin/bash instead

---

doc/CHANGELOG.md
src/Settings/settings.json
tools/genSettings.py

Default font in all operating system is by-default set to monospace font which is incorrect. This PR fixes the default font to fixed font.
Issue: #422  #425

feat(Settings): set the default font to the system fixed-width font

---

tools/updateTranslation.sh
translations/ru_RU.ts
translations/zh_CN.ts

Remove locations in the translations in git, and if the author wants to see the source file at local, he/she can run `tools/updateTranslation.sh r` when editing and run `tools/updateTranslation.sh` after finished.
The location changes are useless and big, which are not good for version control.

refactor(locale): remove locations in the translations

---

doc/CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add an option to check answers on testcases with empty outputs.
Fix #208.

feat: Add option Check On Testcases With Empty Output

---

doc/CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

1. Add auto-save time interval, which can be one of "After the last modification", "After the first modification" or "Without modification".
2. Fix #392.
3. Move the auto-save timer into the MainWindow, which is separated for each tab. This improves performance as it only saves one tab each time.
I think this is better than #412, not only for the functionalities but also for more clear logic and fewer codes.
On Arch Linux.

feat & fix(auto-save): add auto save interval and fix #392

---

src/Telemetry/UpdateChecker.cpp

Skip the changelog of `x.y.z` if:
1. `x.y` is the latest minor (the beta minor version is not counted if check beta update is disabled) version.
2. There's a stable version in the minor `x.y`.
3. `x.y.z` is a beta version.
With the old updater, we have to put only the changelog of the current version in the GitHub Releases.
With the new updater, we can include all changelogs of the minor version when a new stable version is released.
Tested on Arch Linux, with the version set to 6.2.0, and both enabled and disabled beta update.

feat(UpdateChecker): skip beta changelogs in the latest stable minor

---

doc/CHANGELOG.md
src/Settings/AppearancePage.cpp
src/Settings/settings.json
src/Widgets/TestCase.cpp
src/Widgets/TestCase.hpp
src/Widgets/TestCaseEdit.cpp
src/Widgets/TestCases.cpp
src/Widgets/TestCases.hpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Now the width of the input/output/expected of each test case is adjustable, and the maximum height of a test case can be set in the preferences.
This closes #414.

feat(TestCase): adjustable width and customizable max-height

---

doc/CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp

Skip hidden pages when pressing <kbd>Ctrl+Tab</kbd> or <kbd>Ctrl+Shift+Tab</kbd> in the preferces window.
This can make it easier to navigate the settings via keyboard.
On Arch Linux.

feat(PreferencesWindow): Ctrl+Tab and Ctrl+Shift+Tab skip hidden pages

---

CMakeLists.txt
src/Core/EventLogger.cpp
src/Core/Translator.cpp
src/Settings/AppearancePage.cpp
src/Settings/PathItem.cpp
src/Settings/PathItem.hpp
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsInfo.hpp
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/Settings/settings.json
src/main.cpp
tools/genSettings.py
tools/updateTranslation.sh
translations/ru_RU.ts
translations/zh_CN.ts

1. Use `TRKEY` in `PreferencesWindow` to avoid duplicate keys.
2. Convert inline functions in `PathItem` to member functions and use `tr` instead of `QCoreApplication::translate`.
3. Make `SettingsInfo` a class and use `Q_DECLARE_TR_FUNCTIONS` to use `tr` instead of `QCoreApplication::translate`.
4. Move `SettingsInfo.hpp` out of `generated` because it has nothing generated.
5. Remove an extra bracket in `EventLogger` which causes compilation error in platforms other than Linux, Windows and macOS, and causes a warning when updating the translations.
1. Remove duplicates.
2. Use the shorter `tr` instead of the longer `QCoreApplication::translate`.
3. Make `SettingsInfo` more OOP.
4. Fix warnings.
On Arch Linux.

refactor(translation): make codes easier to maintain

---

src/Telemetry/UpdateChecker.cpp
src/Widgets/UpdateProgressDialog.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add a guide to install OpenSSL when the "TLS initialization failed" error happens in the update checker.
This fixes #449.
1. The user will be unable to check for updates in the application without OpenSSL.
2. It's hard and insecure to bundle the OpenSSL in the binary release, because OpenSSL is security-related, if we bundle it, it's hard to fix security problems. This is also why linuxdeployqt doesn't bundle OpenSSL in the AppImage (linuxdeploy/linuxdeploy-plugin-qt#57).

feat(UpdateChecker): add a guide to install OpenSSL

---

src/Telemetry/UpdateChecker.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add the compile-time version of SSL in the warning.
It will be easier for the user to choose a compatible version of OpenSSL.
Tested on Windows 10. I can't test it on Linux because now the PPA is not ready so the AppImage is unavailable, and I can't uninstall `openssl` on my Arch Linux because it's a dependency of many packages.

feat(UpdateChecker): add SSL version in the warning

---

doc/CHANGELOG.md
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesPageTemplate.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsInfo.hpp
src/Settings/settings.json
src/Telemetry/UpdateChecker.cpp
src/Telemetry/UpdateChecker.hpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

Now you can use proxy to check for updates.
In some countries, it's easier to check for updates via proxy.
On Arch Linux, with clash and both Http and Socks5 proxy.

feat(UpdateChecker): add proxy support

---

doc/CHANGELOG.md
src/Settings/AppearancePage.cpp
src/Settings/FontItem.cpp
src/Settings/FontItem.hpp
src/Settings/ValueWrapper.cpp
src/Settings/settings.json
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Now you can set a custom font for the whole application.
This closes #169.
On (my) Windows (with Chinese locale), the default font (SimSun) is not good-looking, and other applications are not using that font. I guess Qt gets the default font from a wrong place. I'm not sure what the reason actually is, but we can solve it by providing the custom application font option.
Tested on Arch Linux with KDE and Windows 10.

feat(Settings): add settings for custom application font

---

src/appwindow.cpp
src/appwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts
ui/appwindow.ui

Add a link to issues in the main menu for troubleshooting.
Now many users are still writing comments in the CF blog instead of opening issues, hopefully this link in the menu can make more users open issues instead of asking elsewhere.
The user can also be redirected to FAQ/Manual/Telegram/Slack because of the new issue page:

feat(menu): add a link to issues in the main menu

---

doc/CHANGELOG.md

Now when you open the Find/Replace dialog with some text selected in the code editor, the text-to-find changes without clearing the undo history.

feat(submodules): update QtFindReplaceDialog and testlib

---

doc/CHANGELOG.md
src/Core/Compiler.cpp
src/Core/Compiler.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Add a warning when failed to start compilation.
There was no message when it failed to start the compilation process.
On Arch Linux.

feat(Compiler): add a warning when failed to start compilation

---

.ci/aur/git/.SRCINFO
.ci/aur/git/PKGBUILD
.ci/aur/stable/.SRCINFO
.ci/aur/stable/PKGBUILD
CMakeLists.txt

Use Ninja to build in the PKBUILD for AUR.
1. Ninja doesn't spam in the terminal like `make`.
2. It is a little bit faster.
Used `makepkg -si` to install the PKGBUILD.

build(aur): use Ninja to build

---

CMakeLists.txt
src/Core/Compiler.cpp
src/Core/Compiler.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/ValueWrapper.cpp
src/Settings/ValueWrapper.hpp
src/Settings/settings.json
src/Util/Util.cpp
src/Util/Util.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Add guessCodec to detect codec.
related issue: #462

feat: Auto detect codec for compiler output

---

doc/CHANGELOG.md
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp

Use the mouse wheel to change the font of code editors. The change is saved in the settings if the changed editor is in a MainWindow (not in a CodeSnippetsPage).
Easier to change the font, and many IDEs support this feature.
On Arch Linux.

feat: use mouse wheel to change the font

---

src/Util/QCodeEditorUtil.cpp

The following warnings are false positive, but it's better to return the value instead of changing a reference.
```
../src/Util/QCodeEditorUtil.cpp: In function ‘void Util::applySettingsToEditor(QCodeEditor*, const QString&)’:
../src/Util/QCodeEditorUtil.cpp:106:40: warning: ‘tabJumpOut’ may be used uninitialized in this function [-Wmaybe-uninitialized]
bool autoComplete, autoRemove, tabJumpOut;
^~~~~~~~~~
In file included from ../third_party/QCodeEditor/include/QCodeEditor:3:0,
from ../src/Util/QCodeEditorUtil.cpp:24:
../third_party/QCodeEditor/include/internal/QCodeEditor.hpp:39:96: warning: ‘autoRemove’ may be used uninitialized in this function [-Wmaybe-uninitialized]
: left(l), right(r), autoComplete(complete), autoRemove(remove), tabJumpOut(jumpout)
^ …
```

refactor(QCodeEditorUtil): fix compiler warning

---

src/Settings/SettingsManager.cpp
src/Settings/SettingsUpdater.cpp

Move renaming editor theme from `SettingsManager` to `SettingsUpdater`.

refactor(SettingsUpdater): rename editor theme in SettingsUpdater

---

src/Settings/PathItem.cpp
src/Settings/PathItem.hpp
src/Settings/ValueWrapper.cpp
src/Settings/settings.json
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

Use enum instead of int for PathItem type.
It's hard to understand what an int id means.

refactor(PathItem): use enum instead of an int id

---

CMakeLists.txt
doc/CHANGELOG.md
src/Settings/CodeSnippetsPage.cpp
src/Settings/DefaultPathManager.cpp
src/Settings/DefaultPathManager.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsInfo.hpp
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/Settings/SettingsUpdater.cpp
src/Settings/settings.json
src/Widgets/TestCaseEdit.cpp
src/Widgets/TestCases.cpp
src/appwindow.cpp
src/mainwindow.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

Add a system to set and change default paths for all choosing path actions.
You can read the tooltips and try it to understand how it works.
It doesn't apply to PathItem because the default path of a PathItem is the old value of it.
It's a part of #269.
Before this, only saving/opening a file can remember the last chosen path, and the rule is hard-coded —— the default path is always the last path you choose.
Now it applies to nearly all choosing path actions, and the rule is very flexible. You can use either a manually set path or an automatically changed path. You can use the same default path for several actions, or even change another action's default path when choosing a path.
On Arch Linux.

feat(Settings): add a flexible system to set and change default paths

---

doc/CHANGELOG.md
src/Extensions/CFTool.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
translations/ru_RU.ts
translations/zh_CN.ts

Add an option to disable toast messages of CF Tool.
Part of #269.
On Arch Linux.

feat(Settings): add an option to disable toast messages of CF Tool

---

tools/updateTranslation.bat
tools/updateTranslation.sh

Add `updateTranslation.bat` for Windows and remove unnecessary arguments of `updateTranslation.sh`.
A screenshot of `lupdate --help`:
On my Windows 10 and Arch Linux.

tools(updateTranslation): support Windows and remove unnecessary arguments

---

doc/CHANGELOG.md
src/Core/MessageLogger.cpp
src/Core/MessageLogger.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsUpdater.cpp
src/Settings/settings.json
src/Widgets/TestCase.cpp
src/Widgets/TestCaseEdit.cpp
src/Widgets/TestCaseEdit.hpp
src/Widgets/TestCases.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Now the test cases loaded from files and program output are elided and read-only if they are too long.
This closes #487.
Users may want to test on big test cases while the performance is good.
On Arch Linux.

feat: elide test cases when they are too long

---

doc/CHANGELOG.md
src/Settings/settings.json

Disable Tab Jump Out Parentheses by default
#498
This feature could be confusing if you don't know it exists.

chore(Settings): disable Tab Jump Out Parentheses by default

---

.github/workflows/release_checksums.yml

Make `dn()` in multi-lines.
Bash functions need to be in multi-lines.

ci: fix release checksums

---

src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp

Before this commit, if there's no old settings file, `loadSettings` won't be executed, but `cur` and `def` are initialized there.
This commit not only fixes the bug, but also refactored the codes, so that the function names are not confusing.
This fixes #503.
On Arch Linux with old settings files deleted.

fix(SettingsManager): fix crash when there's no old settings file

---

doc/CHANGELOG.md
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Add “Duplicate Tab" described in #481.
It opens a new tab with all information saved in hot-exit except the file path.
This closes #481.
For example, I may want to write a brute force solution with the same examples, or try some minor changes without losing the old codes.
On Arch Linux.
@IZOBRETATEL777 @sadykhzadeh you can add the Russian translations.

feat: add duplicate tab

---

translations/zh_CN.ts

The translation was HTML escaped, and the raw HTML was displayed in the UI. Now it isn't and the link is displayed in the UI.
On Windows 10.

fix: fix the zh_CN translation of missing OpenSSL is HTML escaped

---

doc/CHANGELOG.md
src/Core/SessionManager.cpp
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp

Now you can construct a new MainWindow with a `MainWindow::EditorStatus` without opening an untitled tab with a code template at first.
This also fixes the bug that the duplicated tab has the same untitled tab index as the original tab.
This is a part of #191.
It is a waste of time and makes the window title blinking between "untitled" and file paths to open an untitled tab before loading the status.
Tested on Arch Linux. It is about 70% faster when restoring empty files.

perf: load MainWindow::EditorStatus without opening an untitled tab

---

.github/workflows/release.yml
.github/workflows/release_checksums.yml
doc/CHANGELOG.md
src/Telemetry/UpdateChecker.cpp
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

-   Use the Qt installed by aqtinstall to build the AppImage.
-   Added portable/setup in the build info.
-   Fixed the Windows portable suffix in release checksums.
-   Removed the portable version on Linux and macOS.
#454.
The AppImage has been built in my fork and the release is [here](https://github.com/ouuan/cpeditor/releases/tag/release-test).

build: fix release issues

---

doc/CHANGELOG.md
translations/ru_RU.ts
translations/zh_CN.ts
ui/appwindow.ui

As discussed in the Telegram group, now the default shortcut for formatting is changed to <kbd>Ctrl+Shift+I</kbd>.
The translations of shortcuts is also disabled.
On some systems, Ctrl+Alt+L is the default global shortcut for locking the screen, so it's better not to use it.
On Arch Linux.

refactor: disable shortcut translations and change default format shortcut

---

doc/CHANGELOG.md
src/Widgets/DiffViewer.cpp

It uses HTML style instead of palette.
This fixes #519.
Although the palette was set and it was working on Arch Linux with KDE with both Dark Breeze and Dark Fusion, the background is black on Windows with the Dark Fusion theme.
On Windows 10.

fix(DiffViewer): fix background color with Dark Fusion on Windows

---

doc/CHANGELOG.md
src/mainwindow.cpp
src/mainwindow.hpp

Before this commit, the binding is cleared in MainWindow::loadFile before loaded.
On Arch Linux.

fix(FileProblemBinder): fix restoring old problem URL

---

src/mainwindow.cpp

The recent files were not updated when saving the file / restoring the last session, etc. Now it is updated.
On Arch Linux.

fix: update recent files whenever the file path is changed

---

doc/CHANGELOG.md
src/Settings/SettingsManager.cpp

Don't log snippets.
This bug was introduced by moving the path of snippets.
On Arch Linux.

fix: don't log snippets

---

.ci/aur/git/.SRCINFO
.ci/aur/git/PKGBUILD

Add `cpeditor` in the `provides` array of `cpeditor-git`.
So that users can use `cpeditor-git` as an option when they want to install `cpeditor`.

ci(aur): cpeditor-git provides cpeditor

---

doc/CHANGELOG.md
src/Core/Compiler.cpp
src/Core/Compiler.hpp
src/Util/FileUtil.cpp
src/Util/FileUtil.hpp
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add reveal executable files.
This can be a partial solution for #17, because now it's easier to run programs like `gdb` on the executable file.
On Arch Linux.
@IZOBRETATEL777 You can add translations.

feat: reveal executable file

---

.github/workflows/check_srcinfo.yml
.github/workflows/push_aur.yml
.github/workflows/release_aur.yml

1. Check `PKGBUILD` and `.SRCINFO` before pushing to AUR.
2. Check `.SRCINFO` is up to date on each push and PR.
To prevent invalid package (for example, with a missing dependency) and make sure `.SRCINFO` is up to date.
Checking `.SRCINFO` is tested in these commits and this PR. (And [it fails when `.SRCINFO` is not up to date](https://github.com/ouuan/cpeditor/actions/runs/191309899)).
I've tested checking `PKGBUILD` in my fork with some steps like setting the SSH key and pushing to AUR deleted. It fails when checking `.SRCINFO` of `cpeditor-git` after checking `PKGBUILD`, because the `PKGBUILD` is changed after checking `PKGBUILD` as it uses the master branch of `cpeditor/cpeditor` to build the package and uses its version as the version of the package, which is different from the …

ci(aur): check PKGBUILD and verify .SRCINFO is up to date

---

.gitignore
CMakeLists.txt
README.md
doc/CHANGELOG.md
src/Settings/DefaultPathManager.cpp
src/Settings/DefaultPathManager.hpp
src/Settings/settings.json
src/Widgets/ContestDialog.cpp
src/Widgets/ContestDialog.hpp
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Use contest dialogs to open Contests
This commit adds a dialog widget that can be used to open contest. 
Fixes #467 
This is better UI than last one.
Win 10 
**Required translations** @IZOBRETATEL777 and @sadykhzadeh

feat: Use contest dialog to open contest

---

doc/CHANGELOG.md
src/mainwindow.cpp
src/mainwindow.hpp

Now `MainWindow::killProcesses` won't be called twice at the same time, thus the double free is fixed.
This fixes #549.
On Arch Linux.

fix: fix crash when compiling twice with large test cases 

---

.github/workflows/release.yml

Include `.git` in the full source.
Because the full source is of a release, the commit history is not needed, so we can fetch with depth 1.
If you build CP Editor without any commit, `GIT_COMMIT_HASH` will be empty.
In my fork.

ci: include .git in full source

---

doc/CHANGELOG.md
src/Core/Compiler.cpp
src/Core/Compiler.hpp
src/Core/Runner.cpp
src/Core/Runner.hpp

Set the working directory to the output path when executing programs.
To prevent creating files in random places, if you write to files in the code. Perhaps it's also useful in other situations.
On Arch Linux.

feat(Runner): set the working directory to the output path

---

src/Core/Checker.cpp
src/Core/Runner.cpp
src/Extensions/ClangFormatter.cpp
src/Extensions/LanguageServer.cpp
src/Settings/PreferencesPage.hpp
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesPageTemplate.hpp
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/Widgets/TestCase.cpp
src/Widgets/TestCaseEdit.cpp
src/Widgets/TestCases.cpp
src/mainwindow.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

Now we can use `SettingsHelper:getPathXXX` or `SettingsManager::getPathTextXXX` to get the path of a setting in the preferences window.
This reduces duplicated translations, and prevent forgetting to change the path after moving a setting.
On Arch Linux.

refactor: use SettingsHelper::getPath to get the path of a setting

---

doc/CHANGELOG.md
src/Core/Checker.cpp
src/Core/Compiler.cpp
src/Extensions/CompanionServer.cpp
src/Extensions/CompanionServer.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/SettingsUpdater.cpp
src/Settings/ValueWrapper.cpp
src/Settings/settings.json
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

1.  Now the working directory of the compiler and the document path for the language server are the source file path, and `-I <source file path>` is added in the C++ compile command, so that you can easily include headers and compile with the grader, using relative paths and get the correct linting.
2.  Now you can set custom compile command and time limit for each tab.
I took part in [APIO](https://apio2020.id/) today, and found that it's not very easy to solve grader problems with CP Editor (I used `#ifdef OUUAN` during the contest, and the biggest problem was the language server). So these features are added to make it easier to solve grader problems.
The custom compile command and time limit are also helpful without grader problems. For example, you can use different language …

feat: add features for solving grader problems

---

.ci/aur/git/.SRCINFO
.ci/aur/git/PKGBUILD
.ci/aur/stable/.SRCINFO
.ci/aur/stable/PKGBUILD

We now provide user to choose the terminal to perform the detached run. It is not required to have that as an optional dependency.

chore(aur): Remove xterm dependency for detached execution

---

.ci/aur/git/PKGBUILD
.github/workflows/push_aur.yml
CMakeLists.txt

For an unknown reason, the default abbrev for CP Editor is 8 digits now. And somehow it's still 7 digits during CI ([with git 2.28.0](https://github.com/actions/virtual-environments/blame/757f01513062e82bbe8c5670c0b118fafe89e9bc/images/linux/Ubuntu1804-README.md#L183)), so [the CI failed](https://github.com/cpeditor/cpeditor/actions/runs/262574039). This should fix it.
It seems that the reason it is 7 digits during CI is that only the HEAD and its fathers are fetched, and it is 7 digits with only HEAD and its fathers, but 8 digits with all commits.

chore: add --abbrev=8 for git describe

---

doc/CHANGELOG.md
src/mainwindow.cpp

Header comments are now correctly formatted and displayed as mentioned in the linked issue.
See #607
Fixes #607 
For better formatting of code
Arch on KDE
- Header comment starts at first line 
- If header comment is empty 
- A custom header comment with "Powered by CP Editor" 
- A custom header comment without "Powered by CP Editor" 
- Disabled header comment

fix(Head Comments): Improve format and handle edge cases

---

doc/CHANGELOG.md
src/Core/StyleManager.cpp
src/Core/StyleManager.hpp
src/appwindow.cpp
src/mainwindow.cpp

Now the color of the tooltips are controlled by the palette, and the stylesheet is not changed.
This fixes #604 and reverts #606.
1. #604 is caused by unexpected behavior when setting the stylesheet. Instead of changing the order of applying settings, getting rid of the stylesheet has no side effects like #610.
2. I think the new palettes actually seem better than the old stylesheets.
On Arch Linux KDE and Windows, with Dark Fusion and Light Fusion and message logger font changed.

fix(StyleManager): use palette instead of stylesheet for tooltips

---

doc/CHANGELOG.md
src/Settings/settings.json
src/appwindow.cpp
src/appwindow.hpp

Show the preferences window for first-time users.
This closes #192.
Though this is not a guide, I think a guide is somehow redundant, and the homepage of the preferences window is good enough.
First-time users almost definitely need some configuration. This pop-up can help them find where to configure everything and provides a link to the documentation.

feat: show preferences window for first-time users

---

.ci/win/win-setup.iss
CHANGELOG.md

Use the "/norestart" option when installing vcredist,
This fixes #545.

fix(InnoSetup): use the "/norestart" option when installing vcredist

---

src/Settings/SettingsInfo.hpp
src/Settings/SettingsUpdater.cpp
src/Settings/settings.json
src/Widgets/TestCaseEdit.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

1. The old settings keys are moved from SettingsUpdater to settings.json. It reduces the modification when changing the name of a setting, especially when a setting has multiple old names.
2. Rename "Load Test Case Length Limit" to "Display Test Case Length Limit", which is a better name since #491.

refactor(Settings): move old to JSON and rename Test Case Length Limit

---

src/Settings/PreferencesWindow.cpp

PR #627 changed the name of setting in `settings.json` but it was not updated in the `PreferenceWindow.cpp` as a result the application crashed as soon it was launched. It has been fixed in this PR. 
Related to bug introduced in #627 
It is a hotfix. All AUR users who update to new alpha will fail to launch the application
Arch KDE

fix(Preferences): RTE in Debug builds introduced by #627

---

src/Widgets/UpdateProgressDialog.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Update the download links in the update checker from cpeditor.github.io/download to cpeditor.org/<lang>/download.

feat(UpdateChecker): update download links

---

src/Settings/PreferencesPageTemplate.cpp

Emit settingsApplied for immediatelyApply.
SettingsApplied is expected to be emitted in immediatelyApply. If not, we may meet unexpected errors when using immediatelyApply in the future.
On Arch Linux with "Opacity" set to immediatelyApply.
I was thinking of making "Opacity" immediately applied, but when immediately applied it was very slow when draging the slider.

fix(Settings): emit settingsApplied for immediatelyApply

---

CMakeLists.txt
src/Core/Checker.cpp
translations/zh_CN.ts

Use TResult in `testlib.h` instead of a list of numbers.
Use `-Wswitch` to generate a compilation warning when there are unhandled items in TResult.
On Arch Linux with testlib.h checkers and a fake checker which returns an unknown value.

refactor(Checker): use TResult in testlib.h instead of a list of numbers

---

CHANGELOG.md
src/Core/Checker.cpp
src/Core/Checker.hpp
src/mainwindow.cpp

Clear check tasks when starting a new execution.
Otherwise, there can be many unfinished tasks, especially when there are many executions before the checker is compiled.
On Arch Linux.

fix(Checker): clear tasks when starting a new execution

---

src/Core/Checker.cpp
src/Core/Checker.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Add logs for compilation and improve log for killed.
When I was designing the checker, I thought logs for the compilation of the checkers are redundant. But it turns out that it can be very confusing to wait for the checker to be compiled.
On Arch Linux.
@IZOBRETATEL777 Please update the translations.

feat(Checker): add logs for compilation and improve log for killed

---

src/Core/Runner.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Change some `Q_OS_LINUX` to `Q_OS_UNIX`, etc.
Now CP Editor is [in the official repository of FreeBSD 13](https://freebsd.pkgs.org/13/freebsd-amd64/cpeditor-6.6.5.txz.html).
@IZOBRETATEL777 Please update the translation.

feat: improve on non-Linux UNIX platforms

---

src/Settings/CodeSnippetsPage.cpp
src/Settings/CodeSnippetsPage.hpp
src/Settings/ParenthesesPage.cpp
src/Settings/ParenthesesPage.hpp
src/Settings/PreferencesGridPage.cpp
src/Settings/PreferencesGridPage.hpp
src/Settings/PreferencesHomePage.cpp
src/Settings/PreferencesHomePage.hpp
src/Settings/PreferencesPage.cpp
src/Settings/PreferencesPage.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp
src/Widgets/DiffViewer.cpp
src/Widgets/DiffViewer.hpp
src/Widgets/UpdatePresenter.cpp
src/Widgets/UpdatePresenter.hpp
src/Widgets/UpdateProgressDialog.cpp
src/Widgets/UpdateProgressDialog.hpp

First time working on Qt in a while, and needed a warm-up (big project at work), so a little contribution.
This is only part of #541 , the _easy_ part, just removing useless members. I plan to continue working on #541.
#541
Windows 10 (Qt 5.15 lts w/MinGW toolchain)

refactor: use local variables in the constructor instead of class members

---

.github/workflows/release.yml

Use `>> $GITHUB_ENV` to set env.
This fixes #654.

ci(release): use the new syntax to set env

---

CHANGELOG.md
src/appwindow.cpp
src/appwindow.hpp

Toggle full screen by Pressing <kbd>F11</kbd> 
Fixes #642 
Better editing on Smaller screens
Arch on KDE [works]
Windows 10 [Animation to restore to maximized state is bad]
N/A

feat(Window): Toggle Fullscreen with F11

---

src/Core/SessionManager.cpp
src/appwindow.cpp

Repaint after the progress dialog.
The window was sometimes blank after the progress dialog on Windows.
On Windows 10.

fix: repaint after the progress dialog

---

src/Core/EventLogger.cpp
src/Core/EventLogger.hpp
src/Settings/DefaultPathManager.cpp
src/Settings/PreferencesHomePage.cpp
src/Settings/PreferencesHomePage.hpp
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp
src/Settings/SettingsManager.cpp
src/Settings/SettingsUpdater.cpp
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp

1. Add `LOG_DEV` which can be used to check for settings path, etc. which are often mistyped or forgot to update.
2. Check the links on the preferences home page.
On Arch Linux with both debug build and release build.

feat: add LOG_DEV and some warnings

---

src/Settings/PreferencesPageTemplate.cpp

Fix the wrong checkbox style in the preferences window introduced in #659.
On Arch Linux.

fix(PreferencesPageTemplate): don't show label for checkboxes

---

src/Widgets/TestCases.cpp
src/Widgets/TestCases.hpp
src/mainwindow.cpp

Validate test case indices.
Make it safer.
On Arch Linux.

refactor: validate test case indices

---

src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp

This adds the "allowPrefix" parameter for `PreferencesWindow::getPageWidget`.
#659 and #663
There were warnings when clicking links to settings because the old logic was to try removing suffixes from paths until success.
This fixes the false warning and improves performance.
On Arch Linux.

fix(PreferencesWindow): fix warnings when clicking links to settings

---

src/main.cpp

Set AllowSetForegroundWindow on Windows.
This fixes #657 on Windows.
It can be confusing if the running CP Editor doesn't pop up when trying to open the second CP Editor.
And this problem is hard to fix on Linux.
On Windows 10.

fix: set AllowSetForegroundWindow on Windows

---

.gitignore
CHANGELOG.md
CMakeLists.txt
src/Extensions/ClangFormatter.cpp
src/Extensions/CodeFormatter.cpp
src/Extensions/CodeFormatter.hpp
src/Extensions/YAPFormatter.cpp
src/Extensions/YAPFormatter.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp
src/Settings/settings.json
src/Util/FileUtil.cpp
src/Util/FileUtil.hpp
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Better logic and code reuse than #640.
This closes #640.
There are many duplicate codes in #640 and some logics including the `verbose` option are changed. There are also duplicate `format code on save` settings in #640.
On Arch Linux.
@IZOBRETATEL777 please update the translations.

feat(formatter): add YAPF and refactor

---

CHANGELOG.md
src/appwindow.cpp
src/appwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts
ui/appwindow.ui

Add Full Screen in the View menu.
To make it easier to be aware of this feature and reduce the chance that the user doesn't know how to exit full screen.
On Arch Linux.

feat: add Full Screen in the View menu

---

.github/workflows/release.yml

Fix set env.
The new syntax is not a bash script. It doesn't need and doesn't support quotes.

ci(release): fix set env

---

CHANGELOG.md
src/mainwindow.cpp
src/mainwindow.hpp

Show only the Run button for Python.
Make it more reasonable.
On Arch Linux.

feat: show only the Run button for Python

---

.github/ISSUE_TEMPLATE/config.yml
README.md
README_zh-CN.md

The Telegram group will be mentioned only on the website, and the Slack workspace will be deprecated.
The badges are removed because now there are only "downloads@all" and "help wanted issues", which are not very helpful.
@IZOBRETATEL777 you can update the README.

docs: add GitHub Discussions

---

CHANGELOG.md
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/appwindow.cpp

As discussed in #590, I think it was "live-update like QSettings" that I thought was not easy. Simply saving settings on apply should be just fine.
This closes #590.
On Arch Linux.

feat(Settings): save settings to disk on apply

---

.github/workflows/release_checksums.yml

https://github.blog/changelog/2021-01-21-github-actions-short-sha-deprecation/

ci: use full SHA for workflows

---

CHANGELOG.md
CMakeLists.txt
src/Core/Translator.cpp
src/Core/Translator.hpp
src/Settings/PreferencesGridPage.cpp
src/Settings/PreferencesHomePage.cpp
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesPageTemplate.hpp
src/Settings/PreferencesWindow.cpp
src/Settings/PreferencesWindow.hpp
src/Settings/SettingsInfo.hpp
src/Settings/ValueWrapper.cpp
src/Settings/genSettings.py
src/Settings/settings.json
src/Util/Util.cpp
src/Util/Util.hpp
src/Widgets/RichTextCheckBox.cpp
src/Widgets/RichTextCheckBox.hpp
src/Widgets/SupportUsDialog.cpp
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add links to the docs in the preferences window.
Make it easier for the users to find the documentation.
On Arch Linux.

feat(Preferences): add links to the docs in the preferences window

---

src/Core/Checker.cpp
src/Core/Checker.hpp

This fixes #746.
Copy TResult from testlib.h instead of include testlib.h.
This fixes #746.
@sonulohani you can test this.

fix: copy TResult instead of include testlib.h

---

CHANGELOG.md
src/appwindow.cpp

Make Find/Replace a dialog instead of a window.
This makes it a floating window in i3-wm.
On Arch Linux i3-wm.

fix(Find/Replace): make Find/Replace a dialog instead of a window

---

src/main.cpp

In fact, now we are assuming there's only one window, so we'll actually never enable this option again even if #131 is fixed. This closes #131.

fix: completely remove the new window option

---

CHANGELOG.md
src/Core/StyleManager.cpp

Fix selection when Dark Fusion is selected

---

CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/Util/QCodeEditorUtil.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Added configurable text cursor width (https://github.com/cpeditor/cpeditor/issues/781). The text cursor width ranges from 1(default) to 10.

feat: Configurable text cursor width

---

.github/workflows/release.yml

https://github.com/probonopd/linuxdeployqt/commit/a3648aed4ad98bf91d087135a92d08806e52e291
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
This has been tested in ouuan/cpeditor.

ci(release): use Ubuntu 18.04 and fix winlibs tag parsing

---

CHANGELOG.md
src/Settings/settings.json
src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

This PR removes the ESC push button binding for exiting out of the full screen. Additionally, it will show the dialog for the user who has either accidentally pressed F11 or pressed F11 but doesn't know how to restore the window back to normal
https://github.com/cpeditor/cpeditor/issues/786
Esc key will be used to cancel the selection
Ubuntu 21.04

feat: Show dialog on full screen for first time

---

src/appwindow.cpp
src/appwindow.hpp

Update the full-screen state when the window state is changed without triggering the actionFullScreen action.
In i3-wm, tested with Meta+F.

feat: update full-sreen state when WindowState changes

---

src/Settings/PreferencesWindow.cpp
src/appwindow.cpp
src/main.cpp

Q_OS_MAC is deprecated. It includes not only macOS but also other Apple OSs like iOS.
https://doc.qt.io/qt-5/qtglobal.html#Q_OS_MAC

fix: use Q_OS_MACOS instead of Q_OS_MAC

---

CHANGELOG.md
src/Core/Compiler.cpp
src/Core/Compiler.hpp

This fixes #872.
Not tested yet. I bought a new laptop and my Windows dev environment isn't prepared yet.

fix: add ".exe" in the C++ compilation command on Windows

---

VERSIONING.md

Due to [`52fa697`](https://github.com/cpeditor/cpeditor.github.io/pull/140/commits/52fa6977168cade8132c2cf24bef007f78fe709c), now we need to manually trigger the deployment for new minor versions.

docs(VERSIONING): add manual trigger deployment

---

.github/workflows/release.yml
CHANGELOG.md
VERSIONING.md

Include LLVM in the winlibs release.
This could be an out-of-box solution for #824.
At least on my Windows, the clangd downloaded on LLVM official website doesn't recognize `<bits/stdc++.h>` while the one in winlibs does.
https://github.com/ouuan/cpeditor/releases/tag/0.20210617.3

ci(release): include LLVM in the winlibs release

---

CHANGELOG.md
src/mainwindow.cpp

Add file suffix for Default File Path For Problem URLs.
This was introduced in #652.
On Arch Linux.

fix: add suffix for Default File Path For Problem URLs

---

tools/newFile.sh

`${parameter^^}` can't be use in low version bash (e.g. the default bash in macOS),so I changed it to `tr` command.
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

fix(tools): use tr to convert case

---

src/Core/Runner.cpp

Fix: Replace '\0' with ""  in StandardOutput and StandardError. ( #907 )

Fix: Replace '\0' with ""  in StandardOutput and StandardError.

---

CHANGELOG.md
src/Core/Runner.cpp
src/Core/Runner.hpp
translations/ru_RU.ts
translations/zh_CN.ts

cac37ffdc7fd2f05880f9ee5b7107af883d182de uses a temporary file as the stdin of the process instead of using `QProcess::write`, which prevents the main thread from blocking when writing large data to the process on Windows.
1b4d607a827ba6abd9b17e606139d2a87721bdcc is a failed attempt to fix this problem, but it does make the time measurement more accurate on all platforms.
e673712a0db14e005076e72041aacc12fb3e65a9 is another failed attempt which uses QThreadPool.
This fixes #789.
On Arch Linux and Windows 10.

fix: correct time measurement when test cases are large on Windows

---

CHANGELOG.md
src/Core/Checker.cpp
src/Core/Checker.hpp
src/Util/FileUtil.cpp
src/Util/FileUtil.hpp
src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Check the hash of checker's source file to auto re-compile it before run. 
Fixes #843 
macOS 12.0

feat: auto re-compile checker when changed

---

README.md
README_ru-RU.md
README_zh-CN.md
README_zh-TW.md

Now the links stay in the same position after switching to another language.

docs(README): make the positon of languages stable

---

.github/workflows/update-donors.yml

create-pull-request doesn't trigger other actions when using the default GITHUB_TOKEN. It's fine for other actions like check-format, because the targeted base branch is not a protected branch like master. But update-donors is targeted to the master branch, which needs a personal token in order to get the required status checks passing.

ci: use BOT_TOKEN for update-donors

---

CHANGELOG.md
src/appwindow.cpp
src/appwindow.hpp

New tabs were opened at the end of the tab list. Now they are opened next to the current tab, or the original tab if the new tab is a duplicate.
This will likely place related tabs adjacently.
On Arch Linux.

feat: open new tabs adjacent to current tab or duplicated tab

---

DONORS.md
tools/getDonors.py

There's a GitHub Sponsor missing from the donor list. I have no idea why it was not auto-updated. Now the responses from the API are logged.

chore(donors): add missing sponsor and log auto-updater

---

CHANGELOG.md

Undo a Replace All in a single step.
This fixes #1036.
On Arch Linux.

fix: undo a Replace All in a single step

---

CHANGELOG.md
src/appwindow.cpp

Sort case-insensitively when using snippets.
This closes #1063.
On Arch Linux.

fix: sort case-insensitively when using snippets

---

dist/aur/git/PKGBUILD

See https://github.blog/2021-09-01-improving-git-protocol-security-github/

build(aur): use https instead of git protocol

---

CHANGELOG.md
src/Core/SessionManager.cpp
src/appwindow.cpp
src/appwindow.hpp
src/mainwindow.cpp
src/mainwindow.hpp

Save the timestamp when saving the session. When restoring a session, compare the timestamp with the file modification time. If the file is newer than the session, trigger an external file change event.
This should fix #1059.
#1059, and this can also prevent accidentally overriding external file changes when CP Editor is not running.
On Arch Linux,
1.  external file changes when CP Editor is not running
2.  kill CP Editor by `SIGKILL` to simulate abnormal exit

fix: trigger external change handling when reloading sessions

---

CHANGELOG.md
CMakeLists.txt
src/Core/Translator.cpp
src/Settings/settings.json
tools/updateTranslation.bat
tools/updateTranslation.sh
translations/pt_BR.ts
translations/translations.qrc

@crcpucmg, thanks for your contribution!
It would be better if you can invite someone else to review these translations, or you can check them again. It would also be OK if you don't feel like checking again. Tell me when you think this is ready to be merged.
I have invited you to the organization. After accepting the invitation, you'll have write-access to this pull request. If you don't want to make modifications via git/github, you can send me the modified translation file.

feat: add Brazilian Portuguese translations

---

dist/aur/git/PKGBUILD

https://www.reddit.com/r/archlinux/comments/yd6yam/psa_a_recent_git_cve_breaks_all_pkgbuilds/

build(aur/git): apply workaround for git submodule

---

dist/aur/git/PKGBUILD
dist/aur/stable/PKGBUILD

The Arch package changed its name to prepare for KDE 6.

build(aur): add "5" for syntax-highlighting dependency

---

src/Extensions/CompanionServer.cpp
src/Extensions/LanguageServer.cpp
src/Settings/PreferencesPageTemplate.cpp
src/SignalHandler.cpp

MacOS CI was failing due to some checks, those are fixed.
N/A
N/A
N/A

fix: Failing CI on macOS for implicit lambda capture and missing default switch case.

---

CHANGELOG.md
src/Core/MessageLogger.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
translations/el_GR.ts
translations/es_MX.ts
translations/pt_BR.ts
translations/ru_RU.ts
translations/zh_CN.ts
translations/zh_TW.ts

feat: Add option to choose error/warning message colors of message logger
Add two new settings: "Error Message Color" and "Warn Message Color".
These settings are located at Appearance -> General, and have a combo box to select the colors, using default [Qt Colors names](https://doc.qt.io/qt-5/stylesheet-reference.html#color). 
Message Logger code was modified to use these settings instead of hardcoded values.
Closes #521
Some users don't like the default colors for various reasons, so, an option to change them was added.
Tested on Fedora Workstation 37, on dark and light modes.
It's necessary to translate the settings description and also add in the documentation and changelog.

feat: edit error/warning messages color of message logger

---

CMakeLists.txt
cmake/cpeditor.appdata.xml.in

- Use GNUInstallDirs for CMake installation
- Install translation files
- Fix AppData files
Ref: 
https://docs.pagure.org/packaging-guidelines/Packaging%3AAppData.html
https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/
I am trying to make cpeditor packaging for Fedora Linux.

Use GNUInstallDirs; install translation files; Fix AppData files

---

CHANGELOG.md
src/SignalHandler.cpp

Stupid error. `assert` does not run in release mode, so the signal handlers are not registered.
This fixes #1168
On Arch Linux with release mode build.

fix(SignalHandler): properly register signal handlers

---

CHANGELOG.md
src/Editor/CodeEditor.cpp

Add missing key bindings in the new code editor.
It fixes #774 and replaces #1149

fix(CodeEditor): add ESC to cancel selection and correct Home/End behavior

---

src/Editor/CodeEditor.cpp
src/Editor/CodeEditor.hpp

Add back the cursor width setting to the new code editor.
On Arch Linux.

fix: add back the cursor width setting to the new code editor

---

src/mainwindow.cpp

Before this change, the line numbers are incomplete at startup:
Now a resize event of the code editor is triggered at startup to update the geometry of the sidebar.
The solution is similar to #187. I cannot reproduce #187 now, but according to the statement there, a resize should also cover that issue.
On Arch Linux.

fix: incomplete line numbers at startup

---

src/Editor/CodeEditor.cpp
src/Editor/CodeEditor.hpp

Reference: https://forum.qt.io/post/731628
So doing this in QPlainTextEdit is much easier instead of harder than QTextEdit. But this method name is hard to understand...
Previous conversation on this in #516.
On Arch Linux

fix: extra bottom margin

---

src/Editor/KSHRepository.cpp

There are theme names that start with lowercase and uppercase so it's better to sort them case-insensitively.

fix(KSHRepository): sort theme names case-insensitively

---

src/Settings/PreferencesPageTemplate.cpp
src/Settings/SettingsInfo.hpp
src/Settings/genSettings.py
src/Settings/settings.json
src/Util/Util.cpp
translations/el_GR.ts
translations/es_MX.ts
translations/pt_BR.ts
translations/ru_RU.ts
translations/zh_CN.ts
translations/zh_TW.ts

Add `noDoc` option to hide documentation links for simple settings, and some other fixes.
Documentation is missing for some settings and just a duplicate of its name for several settings.

fix: documentation of settings

---

dist/aur/git/PKGBUILD
dist/aur/stable/PKGBUILD

- Add missing dependency `qt5-svg`. It is usually installed (ref: https://pkgstats.archlinux.de/packages/qt5-base and <https://pkgstats.archlinux.de/packages/qt5-svg>, or on your system `pactree -r qt5-svg`). And it seems that CP Editor can run without `qt5-svg`, only the buttons in the "Support Us" dialog are invisible.
- Use SPDX license identifier. ref: https://rfc.archlinux.page/0016-spdx-license-identifiers/
- Don't fetch ECM and KSH in `cpeditor-git`.
- Some cleanup.
Local `makepkg`

build(aur): add qt5-svg & use SPDX license ID & no fetch ECM KSH

---

.github/workflows/build_test.yml
.github/workflows/release.yml

This is a temporary fix to make the CI happy once again since the `macos-latest` now points to macos-14 runners which are based on ARM.
As proposed in https://github.com/cpeditor/cpeditor/discussions/1369 we will eventually plan to go with second option of completely deprecating macOS x64 and going macOS ARM starting v7.0

ci: use macos-13 intel based runner for ci and release

---

CHANGELOG.md
src/Widgets/DiffViewer.cpp

Use the test case font for the diff viewer.
Requested in the Chinese QQ group.
The diff viewer should use the same font as test cases like monospace.
On Arch Linux.
Before:
After:

fix(DiffViewer): use test case font

---

CHANGELOG.md
src/Editor/CodeEditor.cpp
src/Editor/CodeEditor.hpp
src/appwindow.cpp
src/mainwindow.cpp
src/mainwindow.hpp

Remove the function to scale editor font via mouse wheel scroll.
Resolves #1249.
This has been reported to be extremely slow, because it actually applies settings to all tabs besides changing the current editor font.
An option to enable this behavior does not work. Opt-out does not fix the performance issue. Opt-in does not worth it because the user can simply use the font setting to change the font size instead. So this behavior is completely removed.
On Arch Linux.

fix: remove scaling fonts via mouse wheel scroll

---

CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/mainwindow.cpp
src/mainwindow.hpp
translations/el_GR.ts
translations/es_MX.ts
translations/pt_BR.ts
translations/ru_RU.ts
translations/zh_CN.ts
translations/zh_TW.ts

I add a option to disable the CF Tool.
The enable/disable checkbox is at Preferences > Extensions > CF Tool.
If it is disable, the submit button will be hidden and the cf tool won't be checked (so won't show the warning).
Also, I add the Traditional Chinese translations for the descriptions of the checkbox.
ref #1413
OS: Ubuntu 24.04 
Language: English&zh-TW (To check the translation)
1. Use Competitive Companion to get the problems on Codeforces and atcoder.
2. Toggle the enable CF Tool option.
3. Add another codeforces problem.
4. Toggle the enable CF Tool option.

feat: add option to disable CF Tool
