cpeditor/cpeditor

README.md

fix typo of README.md

---

src/DiffViewer.cpp
src/expand.cpp

fixes #29 
Tested on Windows 10, not sure about other OS.

fix(expand, DiffViewer): fixes #29

---

src/mainwindow.cc

fix #14 
https://github.com/coder3101/cp-editor2/issues/14#issuecomment-565082725

fix(mainwindow.cc): fix bugs about saving files

---

src/mainwindow.cc

fixes #28 
(It seems that I lied in https://github.com/coder3101/cp-editor2/issues/14#issuecomment-565227522 . In fact, I haven't learnt Python/JavaScript/PHP before using them, either. I just Google for it when I need to implement something. Same for this PR.)

feat(mainwindow): add verdict colors

---

src/mainwindow.cc

Reverts coder3101/cp-editor2#39

Revert "fix(mainwindow): use simplified instead of trimmed in diff"

---

src/mainwindow.cc

fix(mainwindow): fixes #41

---

README.md

Downloading on Github can be extremely slow (below 10KiB/s) in Mainland China, this link may be useful for them.

chore: add download link for Chinese users

---

include/BaseFiles.hpp
include/IO.hpp
include/Runner.hpp
include/SettingsManager.hpp
include/mainwindow.hpp
src/IO.cpp
src/Runner.cpp
src/SettingsManager.cpp
src/mainwindow.cc
ui/mainwindow.ui

This closes #25.
It hasn't been well tested yet. Maybe I'll check it again tomorrow.
Now, only input1/expected1 has been implemented, 2 and 3 can be added after making sure that 1 works well. (Maybe it's time to kill the 1/2/3 parts.)

feat: add save input and expected

---

README.md
src/UpdateNotifier.cpp
src/appwindow.cpp
win-setup.iss

May be merged after Travis' sync is done.

chore: replace "cp-editor2" with "cp-editor"

---

.gitignore
include/SettingsManager.hpp
include/appwindow.hpp
include/mainwindow.hpp
include/preferencewindow.hpp
src/SettingsManager.cpp
src/appwindow.cpp
src/mainwindow.cc
src/preferencewindow.cpp
ui/appwindow.ui
ui/preferencewindow.ui

I think the editing part is done, maybe needs some testing.
I'll add the "use snippets in the code editor" part tomorrow. Though it should be easy to implement, I don't have time today.

Add snippets

---

ui/preferencewindow.ui

fix(preferencewindow.ui): make snippets buttons wider

---

include/appwindow.hpp
include/mainwindow.hpp
src/appwindow.cpp
src/mainwindow.cc
ui/mainwindow.ui

Reverts coder3101/cp-editor#97

Revert "feat: make file logic like Sublime"

---

include/appwindow.hpp
include/mainwindow.hpp
src/appwindow.cpp
src/mainwindow.cc
ui/mainwindow.ui

Reverts coder3101/cp-editor#99

Revert "Revert "feat: make file logic like Sublime""

---

README.md

i.e. brew and environment variable settings

Add CMake instructions for Mac

---

src/appwindow.cpp

Auto formatting test

---

doc/CHANGELOG.md
src/Settings/AppearancePage.cpp
src/Settings/PathItem.cpp
src/Settings/PreferencesGridPage.cpp
src/Settings/PreferencesGridPage.hpp
src/Settings/PreferencesPage.cpp
src/Settings/PreferencesPageTemplate.cpp
src/Settings/PreferencesWindow.cpp
src/Settings/ShortcutItem.cpp
src/Settings/settings.json
src/Widgets/TestCase.cpp
src/Widgets/TestCases.cpp
src/appwindow.cpp
tools/genSettings.py

Add tooltips for widgets.
This resolves #211 
This makes the buttons and settings easier to understand by new users.

Add Tooltips

---

doc/CHANGELOG.md
src/Settings/FontItem.cpp
src/Settings/FontItem.hpp

fix(FontItem): Fix #260

---

.all-contributorsrc
README.md
README_ru-RU.md
README_zh-CN.md

Manually resolve conflicts for #291, #292, #293, #294, #295, #296, #297, #298, #299, #300, #301, #302, #303, #304, #305, #306, #307, #308, #309, #310, #311, #312, #313, #314.

Add all contributors

---

README_zh-CN.md

docs(README_zh-CN.md): Fix Chinese README

---

doc/CHANGELOG.md

Update the changelog for #334.

docs(changelog): Add change the font of the message logger

---

doc/MANUAL_ru-RU.md
doc/MANUAL_zh-CN.md

Update the old paths of settings in MANUAL_xx-XX.md

doc: Update preference path in manuals

---

src/Extensions/EditorTheme.cpp

In this PR #347, started freeing of stack memory and caused runtime
error during destruction.

fix(EditorThemes): Invalid free/delete

---

.github/workflows/build_test.yml
.github/workflows/check_format.yml
.github/workflows/misspell-fixer.yml
.github/workflows/push_aur.yml
.github/workflows/release_aur.yml
.github/workflows/release_checksums.yml
.github/workflows/release_linux.yml
cmake/aur/.SRCINFO.in
cmake/aur/PKGBUILD.in

- Format workflows.
- Rename full-source-version to version-full-source.
In this way, when there are multiple files downloaded and sorted by file names, the files of the same version are consecutive.

build: rename full source

---

doc/CHANGELOG.md
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/appwindow.cpp
src/appwindow.hpp
ui/appwindow.ui

Add export/import settings.
This closes #336.

feat(Settings): export and import settings

---

src/Settings/settings.json
translations/ru_RU.ts
translations/zh_CN.ts

Add translation for QVariantLists in the settings.

feat(locale): add translation for QVariantLists in the settings

---

src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add an option to allow run program on empty testcases.
Update zh_CN translations.
related issue: #408

feat: Add option Always Run

---

src/Settings/settings.json
src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

fix(Settings): fix "Run On Empty Testcase"

---

README.md

Added that 6.5.2 comes with vcredist bundled
N/A (I think there is no need for such a small problem)
N/A
N/A

doc: update readme to include 6.5.2 vcredist

---

CMakeLists.txt
src/Settings/CodeSnippetsPage.cpp
src/Settings/CodeSnippetsPage.hpp
src/Settings/SettingsManager.cpp
src/Settings/SettingsManager.hpp
src/Settings/SettingsUpdater.cpp
src/Settings/SettingsUpdater.hpp
src/Settings/settings.json
src/appwindow.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

refactor(Settings): add Object type and SettingsUpdater

---

src/Settings/settings.json

Add dependencies for code template settings.

feat(Settings): add dependencies for templates

---

.github/workflows/build_test.yml
.github/workflows/release.yml
CMakeLists.txt

Fix empty display version in GitHub Actions caused by no commit history.

ci: fix empty displayed version in GitHub Actions

---

src/appwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Add translation for build info.

feat: add translation for build info

---

doc/CHANGELOG.md

Add changelog for compiler output codec.

docs(CHANGELOG): add changelog for compiler output codec

---

doc/CHANGELOG.md

The changes in #420 isn't documented yet. I documented these changes.
Document the changes.
I don't think it is needed because it is too small.

docs(CHANGELOG): document the changes in #420

---

src/Core/Checker.cpp

Add missing translations for the checker.

feat(Checker): add missing translations

---

.github/workflows/build_test.yml

Check translations are up-to-date in the build test.
In my fork.

ci: check translations are up-to-date

---

doc/CHANGELOG.md
src/Settings/settings.json
src/appwindow.cpp
src/mainwindow.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts
ui/appwindow.ui

Add "Open Recent Files" in the menu.
On Arch Linux.
@IZOBRETATEL777 Please add Russian translations.

feat: open recent files

---

README.md

docs(README): preferencecs => preferences

---

doc/CHANGELOG.md
src/Widgets/TestCaseEdit.cpp
tools/genSettings.py
translations/ru_RU.ts
translations/zh_CN.ts

Add "save to file" in the context menu of the test cases.
close #529

feat: add 'save to file' in the context menu of the test cases

---

doc/CHANGELOG.md
src/Core/Checker.cpp
src/Core/Checker.hpp
src/Core/Runner.cpp
src/Core/Runner.hpp
src/Widgets/TestCase.cpp
src/Widgets/TestCase.hpp
src/Widgets/TestCases.cpp
src/Widgets/TestCases.hpp
src/mainwindow.cpp
src/mainwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Add TLE and RE verdicts.
https://github.com/cpeditor/cpeditor/pull/565#discussion_r470975717
On Arch Linux.

feat: add TLE and RE verdicts

---

src/mainwindow.cpp
translations/ru_RU.ts
translations/zh_CN.ts

fix a typo from "charachter" to "character
n/a
n/a
n/a (why do we need to test this?)

fix: typo in "character"

---

doc/CHANGELOG.md

Update dependency
Update
Fixes #586 
na
Arch Linux

Update testlib to 0.9.34-SNAPSHOT

---

.github/workflows/build_test.yml
.github/workflows/release.yml

Use Qt 5.15.1, CMake 3.18.2, Ninja 1.10.1.

ci: use Qt 5.15.1

---

doc/CHANGELOG.md
src/Extensions/CFTool.cpp

GYM problems can be submitted through CF Tool. Now, CP Editor will parse them as well.
closes #591 
Arch Linux with CF tool 1.0

feat(CF Tool): Allow submission of GYM Problems 

---

.all-contributorsrc
README.md
README_ru-RU.md
README_zh-CN.md

Add [hall of fame](https://github.com/sourcerer-io/hall-of-fame) in the README.
To highlight new, trending, and top contributors.

docs(README): add hall of fame

---

.gitmodules
CHANGELOG.md
CMakeLists.txt
src/Extensions/CompanionServer.cpp
src/Extensions/CompanionServer.hpp
translations/ru_RU.ts
translations/zh_CN.ts

Fixes #345 (Confirmation required)
It is reported that in some cases the Competitive companion server is skipping some data or not at all accepting valid data on Chrome browser. This could not be reprodduced by us, but a possible solution was to use some other ready made Qt Http Server. In this PR, We use that server to listen for requests sent by Competitive Companion. This should solve the issue. (confirmation required)
Arch Linux with KDE
N/A

refactor(Companion): Use QHttp server

---

.github/pull_request_template.md

Update the PR template.
The old template contains many useless items.

docs: update the PR template

---

translations/zh_CN.ts

Remove the outdated "non-public" in the Chinese translation of main Java class.

fix(translations): fix the Chinese translation of main Java class

---

.github/workflows/push_aur.yml

Checkout master in the push_aur workflow.
Otherwise, it fails on merging two PRs in a row, especially when the last PR is ignored (is a document change).

ci(push-aur): checkout master

---

.github/workflows/check_format.yml
.github/workflows/misspell-fixer.yml

chore: bump create-pull-request from v2 to v3.4.1

---

translations/ru_RU.ts

Update all  uncompleted translations
Resolve Update Translations #664
Ubuntu 20.04 KDE

feat: Update Russian translations

---

.github/stale.yml

https://github.com/probot/stale#usage

chore(stale): update config

---

.github/FUNDING.yml
README.md
README_ru-RU.md
README_zh-CN.md
src/appwindow.cpp
src/appwindow.hpp
translations/ru_RU.ts
translations/zh_CN.ts
ui/appwindow.ui

Opencollective is a Fiscal host for open source projects. The transactions and expenses are tracked by the website and all data is made available to public. It supports many features like Goal to raise funds, One time donations, etc. It is safe and widely available and transparent. 
Our page is located at : https://opencollective.com/cpeditor
N/A
Be ready with funding.
Arch
N/A
N/A

feat: Use opencollective for support

---

.github/workflows/check_format.yml
.github/workflows/misspell-fixer.yml

`${{ github.actor }} ` is added in the PR title because I want to add filters in Gmail to avoid receiving notifications of auto PRs triggered by others.

ci: change the title of auto PRs

---

README.md
README_ru-RU.md
README_zh-CN.md

cpeditor/cpeditor has been unregistered on Codacy.

docs(README): remove Codacy badges

---

.github/FUNDING.yml

chore: delete FUNDING.yml to use the one for the whole organization

---

README.md
README_ru-RU.md
README_zh-CN.md

See sourcerer-io/hall-of-fame#53 and sourcerer-io/sourcerer-app#632.

docs(README): remove hall of fame

---

.ci/win/win-setup.iss
.github/workflows/build_test.yml
.github/workflows/clang_tidy.yml
.github/workflows/release.yml
.github/workflows/release_checksums.yml
CHANGELOG.md

Add x86 releases on Windows.
This closes #719.
demo: https://github.com/ouuan/cpeditor/releases/tag/0.43179.434
It's tested on 64-bit Windows.

ci: add x86 releases on Windows

---

.all-contributorsrc
DONATE.md
DONATE_ru-RU.md
DONATE_zh-CN.md
DONATORS.md
README.md
README_ru-RU.md
README_zh-CN.md

Restructure the README.
Inspired by [nnn](https://github.com/jarun/nnn/blob/c1e673b8304ef286d0f0127ba86e03bcfae6d477/README.md).

docs: restructure README

---

.github/workflows/build_test.yml
.github/workflows/clang_tidy.yml

It seems that cache@v2 was always failing.

ci: use cache@v1

---

translations/ru_RU.ts

Update Russian translations of UI

---

CHANGELOG.md
src/Settings/PreferencesWindow.cpp
src/Settings/settings.json
src/Widgets/TestCases.cpp
translations/ru_RU.ts
translations/zh_CN.ts

Allow editor auto uncheck the accepted testcases.
Add an option for it.
Add Chinese translation.
Closes #734

Auto unchecked accepted testcase

---

src/Settings/settings.json
translations/ru_RU.ts
translations/zh_CN.ts

`settings.json` is also reformatted by Prettier.

feat(Settings): add tips for Auto Uncheck Testcases

---

DONATORS.md

Add GoMage https://www.gomage.com/ for their contribution of $1 toward cpeditor.

chore(donators): add GoMage

---

.gitignore
CMakeLists.txt
cmake/cpeditor.appdata.xml.in

Add metainfo application file because it is required by AppImage and snap packages to get extra information about the application apart from what is present in .desktop file.
#324
Read Description
Fedora 34
N/A

chore: add metainfo xml installation file

---

DONATE.md
DONATE_ru-RU.md
DONATE_zh-CN.md

Now GitHub Sponsors also supports one-time donate.

docs(DONATE): remove one-time / monthly

---

CHANGELOG.md

chore(Changelog): Press Esc to cancel selected text

---

src/main.cpp

fix: fix timeout for SingleApplication

---

CHANGELOG.md
dist/linux/cpeditor.desktop
dist/win/win-setup.iss

Update desktop file(Linux) and Inno Setup file(Windows) to associate files to open in cpeditor.
Closes #855
https://github.com/swift-zym/cpeditor/releases/tag/0.0.8

feat: associate files to be opened in cpeditor

---

.github/workflows/push_snap.yml
.github/workflows/release_snap.yml
dist/snap/snapcraft.yaml

Adds CD pipeline to push automatically on edge snap channel on every push to master, on release of new tag, push the stable build to snap stable channel.
Fixes #456 
Updating and managing of AppImage is not widely known, snaps on the other hand is backed by canonical and ships by default on Ubuntu, making it easier to install cpeditor on those platform, snaps can also be installed on any other Linux distribution.
Tested in Ubuntu focal VM

ci(snap): add pipelines for publishing snap packages

---

.github/workflows/aur-test.yml

Add AUR Build Test.
This can test the git package before it's merged into master and test the stable package before a new release.

ci(aur): add AUR Build Test

---

.github/workflows/aur-test.yml

This fixes https://github.com/cpeditor/cpeditor/pull/858#issuecomment-869008102

ci(aur): use HEAD to test the build of the stable AUR package

---

.github/workflows/aur-test.yml

Try to fix the problem in #911.

ci(aur-test): checkout head.sha instead of github.sha

---

dist/snap/snapcraft.yaml

https://github.com/cpeditor/cpeditor/pull/932#issuecomment-880592483
This actually fixes #931.

build(snap): fix version by adding git

---

translations/zh_TW.ts

Add translation of the application, and review is done by @oToToT and @jw910731.
Some strings that raise Qt Linguist warning are reviewed again and they are correct.
Tested on Kubuntu 21.04.

feat: Add localization for Chinese Traditional (Taiwan)

---

CHANGELOG.md
src/appwindow.cpp
src/appwindow.hpp
src/main.cpp

Change the command-line option --no-hot-exit to --no-restore-session.

---

.github/workflows/update-donors.yml
tools/getDonors.py

ci(donors): keep old donors & rm opencollective/github-sponsors

---

src/Core/MessageLogger.hpp

chore: fix typo in MessageLogger.hpp

---

.github/workflows/push_snap.yml
.github/workflows/release_snap.yml

https://github.com/cpeditor/cpeditor/actions/runs/2505783858
https://github.com/snapcore/action-publish

ci(snap): fix snap login

---

.github/workflows/push_aur.yml
.github/workflows/release.yml
.github/workflows/release_aur.yml
.github/workflows/release_checksums.yml
.github/workflows/release_snap.yml
.github/workflows/update-donors.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: use GITHUB_OUTPUT instead of the set-output command

---

.github/workflows/build_test.yml
.github/workflows/check_format.yml
tools/clangTidyCheck.sh
tools/format.sh

https://github.com/cpeditor/cpeditor/actions/runs/3728095880/jobs/6322803964

ci: upgrade to clang 14

---

.misspell-fixer.ignore
CHANGELOG.md
CMakeLists.txt
src/Core/Translator.cpp
src/Settings/settings.json
tools/updateTranslation.bat
tools/updateTranslation.sh
translations/es_MX.ts
translations/translations.qrc

Added Spanish translations, and the files required for it
This closes #1130

 feat: add Spanish translations

---

.all-contributorsrc
CONTRIBUTING_ja-JP.md
DONATE_ja-JP.md
README.md
README_el-GR.md
README_ja-JP.md
README_ru-RU.md
README_zh-CN.md
README_zh-TW.md

docs: add Japanese translated docs

---

dist/snap/snapcraft.yaml

Copies build scripts to `snapcraft.yaml`.
#1101
#1101 did not update `snapcraft.yaml`, causing snap build to fail. This PR build scripts to `snapcraft.yaml`.
I encountered a strange problem during processing, cmake could not find `Qt5LinguistTools`, so I added an environment variable pointing to `qt515`.
[CI passed successfully](https://github.com/rogeryoungh/cpeditor/actions/runs/5636014221/job/15267633219). Because I don't have a snap environment, I haven't tested it in a real environment.

fix: fix snap build failed

---

.github/workflows/push_snap.yml
.github/workflows/release_snap.yml

https://github.com/cpeditor/cpeditor/actions/runs/10338113647

ci(snap): clone ECM and KSH before building snapcraft

---

.all-contributorsrc
CONTRIBUTING_pt-BR.md
DONATE_pt-BR.md
README.md
README_el-GR.md
README_ja-JP.md
README_pt-BR.md
README_ru-RU.md
README_zh-CN.md
README_zh-TW.md
resources/resources.qrc
src/Core/Translator.cpp

README, CONTRIBUTION and DONATE markdown files translated to Brazilian Portuguese
Related to #664

docs: add Brazilian Portuguese documentation files

---

README.md
README_el-GR.md
README_ja-JP.md
README_pt-BR.md
README_ru-RU.md
README_zh-CN.md
README_zh-TW.md

not sure why the bot created commits but not PR
https://github.com/cpeditor/cpeditor/pull/1419#issuecomment-2561592535

docs: add TheoRiffel as a contributor for translation

---

.github/workflows/build_test.yml
.github/workflows/check_translations.yml

Reverts cpeditor/cpeditor#1445

Revert "ci(build): Use system package for KDE dependencies in macOS and Linux"
